version: '3'
services:
    api-service:
        build:
            context: .
            dockerfile: ./docker-backend.dockerfile
        volumes:
            - .:/app
        restart: always
        ports:
            -   "3002:3000"
        deploy:
            mode: replicated
            replicas: 1
        environment:
            DSN: "host=postgres port=5432 user=postgres password=password dbname=poker sslmode=disable timezone=UTC connect_timeout=5"
        depends_on:
            -   postgres



    postgres:
        image: 'postgres:14.0'
        ports:
            -   "5432:5432"
        restart: always
        deploy:
            mode: replicated
            replicas: 1
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: password
            POSTGRES_DB: poker
        volumes:
            -   ./db-data/postgres/:/var/lib/postgresql/data/
